
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- resources:
  - secrets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sopserator.benfiola.dev
  resources:
  - sopssecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sopserator.benfiola.dev
  resources:
  - sopssecrets/status
  verbs:
  - get
  - patch
  - update
