# permissions for end users to edit sopskeys.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sopskey-editor-role
rules:
- apiGroups:
  - sopserator.benfiola.dev
  resources:
  - sopskeys
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sopserator.benfiola.dev
  resources:
  - sopskeys/status
  verbs:
  - get
