# permissions for end users to view sopssecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sopssecret-viewer-role
rules:
- apiGroups:
  - sopserator.benfiola.dev
  resources:
  - sopssecrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sopserator.benfiola.dev
  resources:
  - sopssecrets/status
  verbs:
  - get
