# permissions for end users to view sopskeys.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sopskey-viewer-role
rules:
- apiGroups:
  - sopserator.benfiola.dev
  resources:
  - sopskeys
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sopserator.benfiola.dev
  resources:
  - sopskeys/status
  verbs:
  - get
